FROM node:22.14.0

WORKDIR /app

RUN sed -i 's/deb.debian.org/mirrors.aliyun.com/g' /etc/apt/sources.list.d/debian.sources && \
    sed -i 's/security.debian.org/mirrors.aliyun.com/g' /etc/apt/sources.list.d/debian.sources

RUN apt-get update && apt-get install -y \
    python3 \
    make \
    g++ \
    git \
    curl \
    && rm -rf /var/lib/apt/lists/*

RUN npm config set registry https://registry.npmmirror.com/ && \
    npm install -g pnpm@9.15.9 && \
    pnpm config set registry https://registry.npmmirror.com/

ENV NODE_ENV=development
ENV NEXT_TELEMETRY_DISABLED=1
ENV BACKEND_INTERNAL_URL=http://backend:11337

COPY package.json pnpm-lock.yaml ./
RUN pnpm install

COPY . .

EXPOSE 4000

CMD ["pnpm", "run", "dev", "--hostname", "0.0.0.0"]
