services:
  # Strapi 后端
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fortune-telling-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      TRANSFER_TOKEN_SALT: ${TRANSFER_TOKEN_SALT}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      APP_KEYS: ${APP_KEYS}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_BASE_URL: ${OPENAI_BASE_URL}
      STRAPI_TELEMETRY_DISABLED: true
      # 数据库连接配置
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      HOST: 0.0.0.0
      BACKEND_PORT: ${BACKEND_PORT}
      DATABASE_SSL: ${DATABASE_SSL}
      DATABASE_FILENAME: ${DATABASE_FILENAME}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - backend_uploads:/app/public/uploads
      - backend_data:/app/.tmp
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${BACKEND_PORT}/api/get-tips"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # Next.js 前端
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: fortune-telling-frontend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_BASE_URL: http://localhost:${BACKEND_PORT}
    ports:
      - "4000:4000"
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

volumes:
  backend_uploads:
  backend_data: